// GENERATED by contracts/script/export-abis.sh — do not edit by hand.

export const deployments = {
  "114": {
    "blockNumber": 33558720,
    "chainId": 114,
    "fxrp": "0x08BA12797a06AEb15c0d535122c1e448259a286f",
    "intentManager": "0x012395820Cc0835727F11D93944b96fc9D668966",
    "intentSettler": "0x38ca2a29AE88DF067f922653A2A7E80f903239c6",
    "liquidityPool": "0x737af7fee3c140eD95F5ad849bD323A634baeC5E",
    "minter": "0xFEE4c92d9A8c130B22754677457Eb3a7d067C28d",
    "priceOracle": "0x5F00A440B87e48A92efddC3CB51bD8dbBA851C1B",
    "relayer": "0x6e27499781eF9bCc2aA978A8c3D17f094a51F578",
    "tokenAddresses": [
      "0x955105c5C17070Acd8b427c6b3e320f457Ea9ae3",
      "0x5eea78c6dAD3FaF1230c96f4D828D100068036d6",
      "0x470F9A2e5Ca8E6baa8616dd9469adf26bf5eE2d4",
      "0x08BA12797a06AEb15c0d535122c1e448259a286f"
    ],
    "tokenDecimals": [
      6,
      6,
      18,
      6
    ],
    "tokenPools": [
      "0x737af7fee3c140eD95F5ad849bD323A634baeC5E",
      "0x6A10C00e1fdEEaa358E4C0367D5054ce970eaA97",
      "0xd5B95501Dd4b147970e42DF37C3DB00219940862",
      "0x0000000000000000000000000000000000000000"
    ],
    "tokenSymbols": [
      "USDC",
      "USDT",
      "WFLR",
      "FXRP"
    ],
    "usdc": "0x955105c5C17070Acd8b427c6b3e320f457Ea9ae3",
    "usesFAssets": false,
    "xrplDepositAddress": "rfh8xAWWrPf51oZZK71SomS41anB6bSUvD",
    "xrplSourceId": "testXRP"
  },
  "31337": {
    "blockNumber": 0,
    "chainId": 31337,
    "fxrp": "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e",
    "intentManager": "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0",
    "intentSettler": "0x0B306BF915C4d645ff596e518fAf3F9669b97016",
    "liquidityPool": "0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f",
    "minter": "0x9A676e781A523b5d0C0e43731313A708CB607508",
    "priceOracle": "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82",
    "relayer": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    "tokenAddresses": [
      "0x322813Fd9A801c5507c9de605d63CEA4f2CE6c44",
      "0x84eA74d481Ee0A5332c457a4d796187F6Ba67fEB",
      "0x4826533B4897376654Bb4d4AD88B7faFD0C98528",
      "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e"
    ],
    "tokenDecimals": [
      6,
      6,
      18,
      6
    ],
    "tokenPools": [
      "0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f",
      "0x9E545E3C0baAB3E08CdfD552C960A1050f373042",
      "0x99bbA657f2BbC93c02D617f8bA121cB8Fc104Acf",
      "0x0000000000000000000000000000000000000000"
    ],
    "tokenSymbols": [
      "USDC",
      "USDT",
      "WFLR",
      "FXRP"
    ],
    "usdc": "0x322813Fd9A801c5507c9de605d63CEA4f2CE6c44",
    "usesFAssets": false,
    "xrplDepositAddress": "rFLARESWAPlocalDevVault1234567890",
    "xrplSourceId": "testXRP"
  }
}
;

export type DeploymentEntry = {
  chainId: number;
  blockNumber?: number;
  intentManager: string;
  intentSettler: string;
  priceOracle: string;
  liquidityPool: string;
  minter: string;
  fxrp: string;
  usdc: string;
  relayer?: string;
  usesFAssets?: boolean;
  xrplDepositAddress?: string;
  xrplSourceId?: string;
};

export function deploymentFor(chainId: number): DeploymentEntry | null {
  const table = deployments as Record<string, unknown>;
  return (table[String(chainId)] as DeploymentEntry | undefined) ?? null;
}
