#!/usr/bin/env bash
# Exports the ABIs the backend and frontend need, plus the deployed-address book.
#
# Emitted as TypeScript modules rather than .json files on purpose: a JSON import needs an
# `with { type: "json" }` attribute under NodeNext ESM, and bundlers disagree about it. A plain
# `export const` works identically in the Node backend and in Next.js with zero config.
#
# Both apps get their own copy rather than sharing a workspace package, which keeps `next build`
# and `tsc` free of cross-package resolution. These files are generated — never hand-edit them.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CONTRACTS_DIR="$ROOT/contracts"
TARGETS=("$ROOT/backend/src/abis" "$ROOT/frontend/src/abis")

NAMES=(
  IntentManager
  IntentSettler
  PriceOracle
  LiquidityPool
  PooledFxrpMinter
  FAssetsMinter
  MockERC20
)

HEADER="// GENERATED by contracts/script/export-abis.sh — do not edit by hand."

cd "$CONTRACTS_DIR"
echo "building contracts..."
forge build >/dev/null 2>&1

for target in "${TARGETS[@]}"; do
  mkdir -p "$target"
  rm -f "$target"/*.json

  # The two consumers disagree about relative-import extensions, and there is no spelling that
  # satisfies both: the backend runs NodeNext ESM, which *requires* the `.js` suffix, while
  # Next.js resolves with `moduleResolution: bundler`, which cannot follow `./X.js` to `X.ts`.
  # So the re-export suffix is chosen per target.
  case "$target" in
    *"/backend/"*) ext=".js" ;;
    *) ext="" ;;
  esac

  index="$target/index.ts"
  printf '%s\n\n' "$HEADER" >"$index"

  for name in "${NAMES[@]}"; do
    {
      echo "$HEADER"
      echo ""
      printf 'export const %sAbi = ' "$name"
      forge inspect "$name" abi --json
      # No `as const`: the TS grammar forbids a line break before `as`, and ethers
      # takes a plain array anyway.
      echo ";"
    } >"$target/$name.ts"

    echo "export { ${name}Abi } from \"./${name}${ext}\";" >>"$index"
  done

  # Address book: every deployments/<chainId>.json merged into one object keyed by chain id.
  {
    echo "$HEADER"
    echo ""
    printf 'export const deployments = '
    if compgen -G "$CONTRACTS_DIR/deployments/*.json" >/dev/null; then
      jq -s 'map({(.chainId | tostring): .}) | add' "$CONTRACTS_DIR"/deployments/*.json
    else
      echo '{}'
    fi
    echo ";"
    echo ""
    echo "export type DeploymentEntry = {"
    echo "  chainId: number;"
    echo "  blockNumber?: number;"
    echo "  intentManager: string;"
    echo "  intentSettler: string;"
    echo "  priceOracle: string;"
    echo "  liquidityPool: string;"
    echo "  minter: string;"
    echo "  fxrp: string;"
    echo "  usdc: string;"
    echo "  relayer?: string;"
    echo "  usesFAssets?: boolean;"
    echo "  xrplDepositAddress?: string;"
    echo "  xrplSourceId?: string;"
    echo "};"
    echo ""
    echo "export function deploymentFor(chainId: number): DeploymentEntry | null {"
    echo "  const table = deployments as Record<string, unknown>;"
    echo "  return (table[String(chainId)] as DeploymentEntry | undefined) ?? null;"
    echo "}"
  } >"$target/addresses.ts"

  echo "exported -> $target"
done

echo "done."
