// GENERATED by contracts/script/export-abis.sh — do not edit by hand.

export const PriceOracleAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "registry_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "CANONICAL_REGISTRY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ftsoV2",
    "inputs": [],
    "outputs": [
      {
        "name": "addr",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getExchangeRateWad",
    "inputs": [
      {
        "name": "sourceFeedId",
        "type": "bytes21",
        "internalType": "bytes21"
      },
      {
        "name": "destFeedId",
        "type": "bytes21",
        "internalType": "bytes21"
      }
    ],
    "outputs": [
      {
        "name": "rateWad",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPrice",
    "inputs": [
      {
        "name": "feedId",
        "type": "bytes21",
        "internalType": "bytes21"
      }
    ],
    "outputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "decimals",
        "type": "int8",
        "internalType": "int8"
      },
      {
        "name": "timestamp",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPriceWad",
    "inputs": [
      {
        "name": "feedId",
        "type": "bytes21",
        "internalType": "bytes21"
      }
    ],
    "outputs": [
      {
        "name": "priceWad",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "timestamp",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getQuote",
    "inputs": [
      {
        "name": "sourceFeedId",
        "type": "bytes21",
        "internalType": "bytes21"
      },
      {
        "name": "destFeedId",
        "type": "bytes21",
        "internalType": "bytes21"
      },
      {
        "name": "sourceAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sourceDecimals",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "destDecimals",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "outputAmount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getUsdValueWad",
    "inputs": [
      {
        "name": "feedId",
        "type": "bytes21",
        "internalType": "bytes21"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "tokenDecimals",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "usdWad",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isWithinSlippage",
    "inputs": [
      {
        "name": "expectedOutput",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "actualOutput",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxSlippageBps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "maxPriceAge",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IFlareContractRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMaxPriceAge",
    "inputs": [
      {
        "name": "newMaxPriceAge",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "slippageFloor",
    "inputs": [
      {
        "name": "expectedOutput",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxSlippageBps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "MaxPriceAgeUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "current",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "FeedDecimalsOutOfRange",
    "inputs": [
      {
        "name": "feedId",
        "type": "bytes21",
        "internalType": "bytes21"
      },
      {
        "name": "decimals",
        "type": "int8",
        "internalType": "int8"
      }
    ]
  },
  {
    "type": "error",
    "name": "FtsoCallFailed",
    "inputs": [
      {
        "name": "feedId",
        "type": "bytes21",
        "internalType": "bytes21"
      }
    ]
  },
  {
    "type": "error",
    "name": "FtsoMalformedResponse",
    "inputs": [
      {
        "name": "feedId",
        "type": "bytes21",
        "internalType": "bytes21"
      }
    ]
  },
  {
    "type": "error",
    "name": "FtsoV2NotRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MaxPriceAgeZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "PriceStale",
    "inputs": [
      {
        "name": "feedId",
        "type": "bytes21",
        "internalType": "bytes21"
      },
      {
        "name": "feedTimestamp",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "nowTimestamp",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxAge",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "PriceZero",
    "inputs": [
      {
        "name": "feedId",
        "type": "bytes21",
        "internalType": "bytes21"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  }
]
;
